#!/usr/bin/env zsh

#
# Path settings
#
typeset -gU path fpath
path=(
    $path
    /usr/local/{,s}bin(N-/)
    ${HOME}/.local/bin(N-/)
)
fpath=(
    ${HOME}/.zfunc(N-/)
    $fpath
)

#
# sheldon initialization
#
eval "$(sheldon source)"

if command -v wt >/dev/null 2>&1; then eval "$(command wt config shell init zsh)"; fi
