[tools]
# Programming Languages
python = "3.12"
go = "1.22"

# Runtimes
node = "latest"
bun = "latest"
deno = "latest"

# Tools
"npm:yarn" = "latest"
"npm:pnpm" = "latest"

[settings]
legacy_version_file_disable_tools = ["terraform"]
experimental = true
