gui:
  showIcons: false
  windowsSize: "full"
  showRandomTip: false
  language: 'en'

git:
  autoFetch: false
  autoRefresh: true
  branchLogCmd: "git log --show-signature --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log --show-signature --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"

refresher:
  refreshInterval: 5
  # fetchInterval: 360

customCommands:
  - key: 'u'
    context: 'files'
    description: 'Stash unstaged files'
    command: 'git stash save --include-untracked'
  - key: 'r'
    context: 'status'
    description: 'Add remote url'
    command: 'git remote add origin "{{index .PromptResponses 0}}" '
    prompts:
      - type: 'input'
        title: 'remote url'
  - key: '<c-c>'
    context: 'commits'
    description: 'Cancel commit'
    command: 'git reset --soft HEAD^'
