[tools]
age = "latest"
atuin = "latest"
bat = "latest"
bitwarden = "latest"
claude = "latest"
codex = "latest"
difftastic = "latest"
direnv = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
go = "1.25.5"
helix = "latest"
herdr = "latest"
hyperfine = "latest"
just = "latest"
lazygit = "latest"
node = "latest"
opencode = "latest"
pinact = "latest"
pnpm = "latest"
starship = "latest"
uv = "latest"
xcodes = "latest"
zellij = "latest"

"cargo:worktrunk" = "latest"
"github:rossmacarthur/sheldon" = "latest"
"npm:typescript-language-server" = "latest"

[settings]
activate_aggressive = true
experimental = true
